module.exports = {
    ACCOUNT_LOOKUP_ERROR     : 'ERR_ACC_LOOKUP_UNKNOWN',
    ACCOUNT_NOT_FOUND        : 'ERR_ACC_NO_RESULT',
    ACCOUNT_TOKEN_INVALID    : 'ERR_ACC_BAD_TOKEN',
    ACCOUNT_AUTH_NOT_STARTED : 'ERR_ACC_AUTH_START',
    ACCOUNT_NOT_AUTHED       : 'ERR_ACC_NO_AUTH',
    ACCOUNT_IS_AUTHED        : 'ERR_ACC_IS_AUTH',
    ACCOUNT_ALREADY_AUTHED   : 'ERR_ACC_ALREADY_AUTH',
    ACCOUNT_SAVE_ERROR       : 'ERR_ACC_SAVE_UNKNOWN',

    AUTH_NOT_APPROVED        : 'ERR_AUTH_UNAPPROVED',

    PLAYER_NOT_FOUND         : 'PLAYER_DOES_NOT_EXIST',

    REQUEST_ERROR            : 'ERR_REQ_UNKNOWN',
    REQUEST_NOT_SUCCESSFUL   : 'ERR_REQ_NOT_200',

    COULD_NOT_GET_RANK       : 'ERR_RANK_GET_FAIL',

    DATABASE_ERROR           : 'ERR_DB_UNKNOWN',
    DATABASE_NULL_RESULT     : 'ERR_DB_BAD_RESULT'
};